-- MySQL Script generated by MySQL Workbench
-- Tue 17 Jan 2017 12:31:17 AM CET
-- Model: oust-function    Version: 1.0
-- Authors: Tano Iannetta, Loan Lassalle et Jérémie Zanone
-- MySQL Workbench Forward Engineering

DELIMITER $$

USE `oust`$$

DROP FUNCTION IF EXISTS `oust`.`nextDayOfWeek` $$
CREATE DEFINER = CURRENT_USER FUNCTION `oust`.`nextDayOfWeek` (dateBegin TIMESTAMP, dayName VARCHAR(9)) RETURNS TIMESTAMP
BEGIN
	DECLARE i TINYINT;
    DECLARE dateReached TIMESTAMP;
	SET @i = 1;
    
	WHILE @i <= 7 DO
		SET @dateReached = DATE_ADD(dateBegin, INTERVAL @i day);
		IF DAYNAME(@dateReached) = dayName THEN
			RETURN @dateReached;
		END IF;
		SET @i = @i + 1;
    END WHILE;
    
	RETURN @dateReached;
END $$


DROP PROCEDURE IF EXISTS `oust`.`missionOfDate` $$
CREATE DEFINER = CURRENT_USER PROCEDURE `oust`.`missionOfDate` (IN dateMission TIMESTAMP)
BEGIN
    SELECT 
        c.nom,
        c.prenom,
        c.adresse_rue,
        c.adresse_numero,
        c.adresse_code_postal,
        loc.localite,
        com.commune,
        com.canton,
        dech.dechetterie
    FROM
        localite AS loc
            INNER JOIN
        commune AS com ON loc.commune_id = com.commune_id
            INNER JOIN
        dechetterie AS dech ON loc.dechetterie_id = dech.dechetterie_id
            INNER JOIN
        client AS c ON loc.localite_id = c.localite_id
    WHERE
         TIMESTAMPDIFF(day, c.prochain_passage, dateMission) = 0;
END$$