-- MySQL Script generated by MySQL Workbench
-- Mon 28 Dec 2016 09:46:33 PM CET
-- Model: oust-data    Version: 1.0
-- Authors: Tano Iannetta, Loan Lassalle et Jérémie Zanone
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

USE oust;

-- -----------------------------------------------------
-- Table `oust`.`commune`
-- -----------------------------------------------------
SET AUTOCOMMIT=0;
INSERT INTO commune VALUES(1,'Lausanne','Vaud', NULL),(2,'Aubonne','Vaud', NULL),(3,'Allaman','Vaud', NULL),(4,'Ballaigues','Vaud', NULL),(5,'Bex','Vaud', NULL),(6,'Bussigny','Vaud', NULL),(7,'Estavayer','Fribourg', NULL),(8,'Belmont-Broye','Fribourg', NULL),(9,'Payerne','Vaud', NULL),(10,'Cossonay','Vaud', NULL);
COMMIT;


-- -----------------------------------------------------
-- Table `oust`.`dechetterie`
-- -----------------------------------------------------
SET AUTOCOMMIT=0;
INSERT INTO dechetterie VALUES(1,'Estavayer-le-Lac',245243.45243, 548.45,'Bernard','Monday, Tuesday, Wednesday','8:00-12:00, 13:00-17:00','+41794548614',1,NULL, NULL),(2,'Payerne',244743.443, 58.425,'Jean-Neige','Monday, Tuesday, Sunday','7:00-17:00','+41795523487',0,NULL, NULL),(3,'Lausanne',NULL,NULL,'Michel','Monday, Tuesday, Wednesday, Thursday, Friday','7:00-17:00','+41795458687',1,NULL, NULL);
COMMIT;


-- -----------------------------------------------------
-- Table `oust`.`localite`
-- -----------------------------------------------------
SET AUTOCOMMIT=0;
INSERT INTO localite VALUES(1,'Lausanne',1,3, NULL),(2,'Estavayer-le-Lac',7,1, NULL),(3,'Murist',7,1, NULL),(4,'Domdidier',8,1, NULL),(5,'Payerne',9,2, NULL);
COMMIT;


-- -----------------------------------------------------
-- Table `oust`.`contrat`
-- -----------------------------------------------------
SET AUTOCOMMIT=0;
INSERT INTO contrat VALUES(1,'2016-06-25',NULL,'aucun',0, NULL),(2,'2016-08-04',NULL,'prélèvement automatique',1, NULL),(3,'2016-08-04',NULL,'carte bancaire',1, NULL),(4,'2017-01-01',NULL,'espèces',1, NULL),(5,'2017-01-09',NULL,'aucun',0, NULL),(6,'2017-01-04',NULL,'aucun',0, NULL),(7,'2017-01-12',NULL,'prélèvement automatique',1, NULL),(8,'2017-01-11',NULL,'aucun',0, NULL),(9,'2017-01-14',NULL,'carte bancaire',1, NULL),(10,'2017-01-10',NULL,'espèces',1, NULL);
COMMIT;


-- -----------------------------------------------------
-- Table `oust`.`formule`
-- -----------------------------------------------------
SET AUTOCOMMIT=0;
INSERT INTO formule VALUES(1,'Basique 1 mois',1,20,1, NULL),(2,'Basique 3 mois',3,20,1, NULL),(3,'Basique 6 mois',6,20,1, NULL),(4,'Basique 12 mois',12,20,1, NULL),(5,'Standard 1 mois',1,35,2, NULL),(6,'Standard 3 mois',3,35,2, NULL),(7,'Standard 6 mois',6,35,2, NULL),(8,'Standard 12 mois',12,35,2, NULL),(9,'Premium 1 mois',1,55,4, NULL),(10,'Premium 3 mois',3,55,4, NULL),(11,'Premium 6 mois',6,55,4, NULL),(12,'Premium 12 mois',12,55,4, NULL),(13,'Special',1,110,1, NULL);
COMMIT;


-- -----------------------------------------------------
-- Table `oust`.`client`
-- -----------------------------------------------------
SET AUTOCOMMIT=0;
INSERT INTO client VALUES(1,'Monneron','Yoann','Rte du Port',9,1470,5,NULL,NULL,'+41791111111','wesh@hot.com','CH3298423984',NULL,'Tuesday','3e étage', NULL),(2,'Iannetta','Tano','Rte de la Ferme',14,1350,3,NULL,NULL,'+41791166611','love@hotdog.com','CH1111423984',NULL,'Tuesday','15e étage', NULL),(3,'Lassale','Loan','Chemin du coquin',101,1004,4,NULL,NULL,'+41791142311','burger@macdo.com','CHerr98423984',NULL,'Sunday',NULL, NULL),(4,'Zanone','Jérémie','Avenue du conifère',64,1542,2,NULL,NULL,'+41791134671','velo@vtt.com','CH98ss23984',NULL,'Saturday',NULL, NULL),(5,'Galois','Maxime','Route de la boulangerie',6,1420,1,NULL,NULL,'+41791154671','kiwi@sakila.com','CH98ff78254',NULL,'Monday',NULL, NULL),(6,'Pritz','Jean','Chemin des Acacias',6,1006,1,NULL,NULL,'+41791156541','jean.pritz@facebook.com','CH98ff27454',NULL,'Thursday',NULL, NULL),(7,'Rut','Marie','Route de Berne',10,1004,5,NULL,NULL,'+41791195171','marie.rut@yahoo.com','CH98ffb44',NULL,'Saturday',NULL, NULL),(8,'Flaine','Sophie','Avenue de Genève',52,1546,2,NULL,NULL,'+41791151231','rougeCitron@hotmail.com','CH98ffd5h54',NULL,'Wednesday',NULL, NULL),(9,'Claire','Anne','Chemin du Grand Duc',13,1000,1,NULL,NULL,'+41791199671','luxeMix@gmail.com','CH98ff27999',NULL,'Thursday',NULL, NULL),(10,'George','Camille','Rue Bill Gates',26,1380,4,NULL,NULL,'+41797454671','hackMan@rust.com','CH98f78d454',NULL,'Saturday',NULL, NULL);
COMMIT;


-- -----------------------------------------------------
-- Table `oust`.`prestation`
-- -----------------------------------------------------
SET AUTOCOMMIT=0;
INSERT INTO prestation VALUES(1,1,1,'2017-01-17',NULL, NULL),(2,2,4,'2017-01-17',NULL, NULL),(3,3,4,'2017-01-14',NULL, NULL),(4,4,3,'2017-01-02',NULL, NULL),(5,5,5,'2017-01-09',NULL, NULL),(6,6,6,'2017-01-14',NULL, NULL),(7,7,7,'2017-01-06',NULL, NULL),(8,8,4,'2017-01-17',NULL, NULL),(9,9,8,'2017-01-15',NULL, NULL),(10,10,10,'2017-01-17',NULL, NULL);
COMMIT;


-- -----------------------------------------------------
-- Table `oust`.`boite`
-- -----------------------------------------------------
SET AUTOCOMMIT=0;
INSERT INTO boite VALUES(1,'Grande',15,NULL,'louée','2017-06-30',NULL, NULL),(2,'Grande',15,NULL,'louée','2017-06-06',NULL, NULL),(3,'Petite',15,NULL,'en stock',NULL,NULL, NULL),(4,'Grande',15,NULL,'en stock',NULL,NULL, NULL),(5,'Grande',15,NULL,'en stock',NULL,NULL, NULL),(6,'Grande',15,NULL,'en stock',NULL,NULL, NULL),(7,'Petite',5,NULL,'achetée',NULL,NULL, NULL),(8,'Petite',5,NULL,'achetée',NULL,NULL, NULL),(9,'Grande',15,NULL,'achetée',NULL,NULL, NULL);
COMMIT;


-- -----------------------------------------------------
-- Table `oust`.`vehicule`
-- -----------------------------------------------------
SET AUTOCOMMIT=0;
INSERT INTO vehicule VALUES(1,'FR200488','Fiat Punto',100000, NULL),(2,'FR278842','Trolley-Bus',666, NULL),(3,'FR103289','Ferrari',1, NULL),(4,'DEADBEEF','Lamborghini Aventador',10000, NULL);
COMMIT;


-- -----------------------------------------------------
-- Table `oust`.`droits_acces`
-- -----------------------------------------------------
SET AUTOCOMMIT=0;
INSERT INTO droits_acces VALUES(1,'Administrateur','Les droits administrateurs permettent un accès total.', NULL),(2, 'Manager','Les droits managers permettent la visualisation et modification des données.', NULL),(3,'Opérateur','Les droits opérateurs permettent la visualisation des clients et modifications des tournées.', NULL);
COMMIT;


-- -----------------------------------------------------
-- Table `oust`.`employe`
-- -----------------------------------------------------
SET AUTOCOMMIT=0;
INSERT INTO employe VALUES(1,'Rosset','Joel','Chemin du Bel-Air',9,1470,1,'+41792345678','joel.rosset@bluewin.ch','CH3278923984','1000000',1,'BigBoss','mouton',NULL, NULL),(2,'Rosset','Christophe','Chemin du Bel-Air',9,1470,2,'+41792345679','christophe.rosset@bluewin.ch','CH3278923985','1000000',1,'BigBoss2','mouton2',NULL, NULL);
COMMIT;


-- -----------------------------------------------------
-- Table `oust`.`mission`
-- -----------------------------------------------------
SET AUTOCOMMIT=0;
INSERT INTO mission VALUES(NULL,1,1,1,3,300,NULL, NULL),(NULL,1,2,1,3,750,NULL, NULL),(NULL,4,2,2,3,1200,NULL, NULL),(NULL,5,2,1,2,70,NULL, NULL),(NULL,3,2,2,5,10,NULL, NULL);
COMMIT;





SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
